### PR TITLE
Name the cop levels to imply strictnes

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Sure, I like it. @mcorr maybe can you find a better word than "lenient"? Feels weird to me.

**Comment by ezr-ondrej** [comment]
only think I can think of is `loose` (sounds bit worse then `lenient`), `libarate` (sounds political xD)

**Comment by lzap** [comment]
@melcorr RuboCop is a Ruby static code analyzer (a.k.a. linter) and code formatter. Out of the box it will enforce many of the guidelines outlined in the community Ruby Style Guide. Apart from reporting the problems discovered in your code, RuboCop can also automatically fix many of them for you. (From its homepage).

We have two groups of rules, one which is more strict (opinionated) and one that is more loose. Which terms to use?

**Comment by melcorr** [comment]
IMO, lenient > loose 

strict/gentle
strict/forgiving
strict/tolerant 
strict/permissive

**Comment by ezr-ondrej** [comment]
@lzap I'd roll with the lenient if you don't insist, if you do, I'd go with `permissive`

**Review by lzap — APPROVED** [review]
Your call! I am good then.

**Pull request merged**
