### PR TITLE
Upgrade RuboCop version to 1.60.0

### PR DESCRIPTION
**Pull request by archanaserver**
This is part of Rubocop standerdization, link for the reference: https://community.theforeman.org/t/standardizing-rubocop-with-theforeman-rubocop/37239

### CODE REVIEW

**Comment by ekohl** [comment]
As discussed, please create some PR to a user of this gem to see how it performs.

**Comment by ekohl** [comment]
I started with a PR to REX to fix some cops: https://github.com/theforeman/foreman_remote_execution/pull/848

Then I'd like you to submit more PRs with the actual updates. One example is https://github.com/ekohl/foreman_remote_execution/commit/e07dfde3555bb16fd013f09171e81f1c693949b5.

**Comment by archanaserver** [comment]
> I started with a PR to REX to fix some cops: [theforeman/foreman_remote_execution#848](https://github.com/theforeman/foreman_remote_execution/pull/848)
> 
> Then I'd like you to submit more PRs with the actual updates. One example is [ekohl/foreman_remote_execution@e07dfde](https://github.com/ekohl/foreman_remote_execution/commit/e07dfde3555bb16fd013f09171e81f1c693949b5).

Thanks @ekohl, I've started with the `foreman_maintain`: https://github.com/theforeman/foreman_maintain/pull/789

**Comment by ekohl** [comment]
Another thing to note: foreman itself only uses theforeman-rubocop 0.0.6 today. It would also be good to see what would happen if you update that.

**Comment by archanaserver** [comment]
@ekohl are the following PRs ready for review and merging, including this one?

https://github.com/theforeman/theforeman-rubocop/pull/11 https://github.com/theforeman/theforeman-rubocop/pull/9

**Review by ehelms — APPROVED** [review]

**Pull request merged**
